### DISCUSSION TITLE
How to change default port?

### DISCUSSION THREAD

**Discussion by blogdemoi** [ArchiveBox/ArchiveBox#1133] [Q&A] [answered]
Hi,

I just installed ArchiveBox on a Raspberry Pi (with the recommended docker compose method) and I would like to change the default port 8000 to another one as 8000 is already in use.

Do I have to do this in ArchiveBox.conf and if so how?

Thank you.

**Comment by pirate** [comment, marked as answer]
You can just edit the `ports` section of the `docker-compose.yml` file.

```yaml
...
command: server --quick-init 0.0.0.0:9000
ports:
  - 9000:9000
```
