### DISCUSSION TITLE
Docker scheduling docs questions

### DISCUSSION THREAD

**Discussion by thelfensdrfer** [ArchiveBox/ArchiveBox#1375] [General]
Hi, I have a few questions about this wiki page: https://github.com/ArchiveBox/ArchiveBox/wiki/Scheduled-Archiving#docker-usage

1. I read somewhere, but can't find it anymore, that you shouldn't use `docker-compose exec archivebox_scheduler ...` but `docker-compose run archivebox_scheduler ...`. Is that true, and if so, why?
2. As far as I understand, without `--overwrite` one URL is only archived once, no matter if I also provide e.g. a `--every=day` argument. At least that's how I understand this example: https://github.com/ArchiveBox/ArchiveBox/wiki/Scheduled-Archiving#example-archive-a-reddit-subreddit-and-discussions-for-every-post-once-a-week
  But if that's true, the following examples with Reddit, hacker news, the RSS feed, etc. are all missing the overwrite flag.
3. Since now I also added all my URLs (the content did not change) without the overwrite flag and I suspect that's the reason I didn't see any new archive results in the web UI. But I can see that the scheduler worked when reading the docker logs. In the web UI the logs do not contain any new information since the initial archive result 5 weeks ago. For me it always seemed like it didn't run properly until I checked the docker logs.

**Comment by pirate** [comment]
> I read somewhere, but can't find it anymore, that you shouldn't use `docker-compose exec archivebox_scheduler ...` but `docker-compose run archivebox_scheduler ...`. Is that true, and if so, why?

Because `docker compose run` goes through the `./bin/docker_entrypoint.sh`, which is needed to do a bunch of filesystem checks on startup and drop down to the `archivebox` user with the correct permissions. `docker compose exec`/`docker exec` skip the entrypoint entirely and don't use the right permissions.

(side note: `docker compose` without the `-` is much faster and has a nicer-looking CLI than `docker-compose` these days)

---

> As far as I understand, without `--overwrite `one URL is only archived once, no matter if I also provide e.g. a `--every=day` argument. At least that's how I understand this example: ...

That is correct, but the intention is to use it with `--depth=1` so that all new URLs found *within* the page are archived, even if the root URL is not. This is perfect for archiving HN, subreddits, etc. any kind of feed. I don't need a snapshot of the HN homepage every day, what I really want is a snapshot of all the *articles* and *comment sections* linked to from the homepage since thats where the real content is.

---

> In the web UI the logs do not contain any new information since the initial archive result 5 weeks ago [...] For me it always seemed like it didn't run properly until I checked the docker logs.

This could be caused by a number of things, will need more info to debug. Please share your full `docker-compose.yml`, and the output of `docker compose run archivebox version` and `docker compose run archivebox schedule --show`.

**Reply by thelfensdrfer** [reply]
Thanks for your detailed response. 

I already use `docker compose`, I just copied the command from the wiki. 

The `overwrite` flag makes sense to me now, it wasn't clear to me that external URLs (or nested URLs) are still added, even though the initial URL did not change.

My `docker-compose.yml`:

```yml
version: '3.9'

x-logging: 
  &default-logging
  driver: gelf     
  options:
    gelf-address: "tcp://****:12201"

services:
    archivebox:
        image: archivebox/archivebox:dev
        command: server --quick-init 0.0.0.0:8000
        expose:
            - 8000
        volumes:
            - ./data:/data
            - ./etc/crontabs:/var/spool/cron/crontabs
        environment:
            - VIRTUAL_HOST=archive.****
            - VIRTUAL_PORT=8000
            - LETSENCRYPT_HOST=archive.****
            - LETSENCRYPT_EMAIL=****@gmail.com
            - ALLOWED_HOSTS=archive.****
            - PUBLIC_INDEX=False
            - PUBLIC_SNAPSHOTS=False
            - PUBLIC_ADD_VIEW=False
            - ADMIN_USERNAME=****
            - ADMIN_PASSWORD=****
            - PUID=1000                        
            - PGID=1000
            - SEARCH_BACKEND_ENGINE=sonic     
            - SEARCH_BACKEND_HOST_NAME=sonic
            - SEARCH_BACKEND_PASSWORD=****
            - MEDIA_MAX_SIZE=100m
            - TIMEOUT=60
            - CHECK_SSL_VALIDITY=True         
            - SAVE_ARCHIVE_DOT_ORG=True     
        logging: *default-logging
        networks:
            - proxy
            - default

    sonic:
       image: valeriansaliou/sonic:latest
       expose:
           - 1491
       environment:
           - SEARCH_BACKEND_PASSWORD=****
       volumes:
           - ./sonic.cfg:/etc/sonic.cfg:ro
           - ./data/sonic:/var/lib/sonic/store
       logging: *default-logging
    
    archivebox_scheduler:
       image: ${DOCKER_IMAGE:-archivebox/archivebox:dev}
       command: schedule --foreground
       environment:
           - MEDIA_MAX_SIZE=100m               # increase this number to allow archiving larger audio/video files
           - TIMEOUT=60                      # increase if you see timeouts often during archiving / on slow networks
           - ONLY_NEW=True                   # set to False to retry previously failed URLs when re-adding instead of skipping them
           - CHECK_SSL_VALIDITY=True         # set to False to allow saving URLs w/ broken SSL certs
           - SAVE_ARCHIVE_DOT_ORG=True       # set to False to disable submitting URLs to Archive.org when archiving
           - PUID=1000                        # set to your host user's UID & GID if you encounter permissions issues
           - PGID=1000
       volumes:
           - ./data:/data
           - ./etc/crontabs:/var/spool/cron/crontabs
       logging: *default-logging

networks:
  proxy:
    external: true
    name: proxy
```

`docker compose run archivebox version`: 
```
0.7.3
ArchiveBox v0.7.3+editable COMMIT_HASH=62183b4 BUILD_TIME=2024-03-02 13:07:03 1709384823
IN_DOCKER=True IN_QEMU=False ARCH=x86_64 OS=Linux PLATFORM=Linux-4.18.0-513.11.1.el8_9.x86_64-x86_64-with-glibc2.36 PYTHON=Cpython
FS_ATOMIC=True FS_REMOTE=True FS_USER=1000:1000 FS_PERMS=644
DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND=sonic LDAP=False

[i] Dependency versions:
 √  PYTHON_BINARY         v3.11.8         valid     /usr/local/bin/python3.11                                                   
 √  SQLITE_BINARY         v2.6.0          valid     /usr/local/lib/python3.11/sqlite3/dbapi2.py                                 
 √  DJANGO_BINARY         v3.1.14         valid     /usr/local/lib/python3.11/site-packages/django/__init__.py                  
 √  ARCHIVEBOX_BINARY     v0.7.3          valid     /usr/local/bin/archivebox                                                   

 √  CURL_BINARY           v8.5.0          valid     /usr/bin/curl                                                               
 √  WGET_BINARY           v1.21.3         valid     /usr/bin/wget                                                               
 √  NODE_BINARY           v20.11.1        valid     /usr/bin/node                                                               
 √  SINGLEFILE_BINARY     v1.1.46         valid     /app/node_modules/single-file-cli/single-file                               
 √  READABILITY_BINARY    v0.0.11         valid     /app/node_modules/readability-extractor/readability-extractor               
 √  MERCURY_BINARY        v1.0.0          valid     /app/node_modules/@postlight/parser/cli.js                                  
 √  GIT_BINARY            v2.39.2         valid     /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY      v2023.12.30     valid     /usr/local/bin/yt-dlp                                                       
 √  CHROME_BINARY         v121.0.6167.57  valid     /usr/bin/chromium-browser                                                   
 √  RIPGREP_BINARY        v13.0.0         valid     /usr/bin/rg                                                                 

[i] Source-code locations:
 √  PACKAGE_DIR           23 files        valid     /app/archivebox                                                             
 √  TEMPLATES_DIR         3 files         valid     /app/archivebox/templates                                                   
 -  CUSTOM_TEMPLATES_DIR  -               disabled  None                                                                        

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled  None                                                                        
 -  COOKIES_FILE          -               disabled  None                                                                        

[i] Data locations:
 √  OUTPUT_DIR            6 files @       valid     /data                                                                       
 √  SOURCES_DIR           480 files       valid     ./sources                                                                   
 √  LOGS_DIR              2 files         valid     ./logs                                                                      
 √  ARCHIVE_DIR           31 files        valid     ./archive                                                                   
 √  CONFIG_FILE           81.0 Bytes      valid     ./ArchiveBox.conf                                                           
 √  SQL_INDEX             504.0 KB        valid     ./index.sqlite3 
```


`docker compose run archivebox schedule --show`:
```
[i] [2024-03-11 11:30:33] ArchiveBox v0.7.3: archivebox schedule --show
    > /data

@daily cd /data && /usr/local/bin/archivebox add --depth=1 "https://****" >> /data/logs/schedule.log 2>&1 # archivebox_schedule
@daily cd /data && /usr/local/bin/archivebox add --depth=1 "https://****" >> /data/logs/schedule.log 2>&1 # archivebox_schedule
@daily cd /data && /usr/local/bin/archivebox add --depth=1 "https://****" >> /data/logs/schedule.log 2>&1 # archivebox_schedule
@daily cd /data && /usr/local/bin/archivebox add --depth=1 "https://****" >> /data/logs/schedule.log 2>&1 # archivebox_schedule
@daily cd /data && /usr/local/bin/archivebox add --depth=1 "https://****" >> /data/logs/schedule.log 2>&1 # archivebox_schedule
@daily cd /data && /usr/local/bin/archivebox add --depth=1 "https://****" >> /data/logs/schedule.log 2>&1 # archivebox_schedule
```

`docker compose logs archivebox_scheduler --tail 100 -t`:
```
archivebox_scheduler-1  | 2024-03-02T14:01:14.859088883Z [i] [2024-03-02 14:01:14] ArchiveBox v0.7.3: archivebox schedule --foreground
archivebox_scheduler-1  | 2024-03-02T14:01:14.859303665Z     > /data
archivebox_scheduler-1  | 2024-03-02T14:01:14.859359245Z 
archivebox_scheduler-1  | 2024-03-02T14:01:18.279118884Z [*] Running 6 ArchiveBox jobs in foreground task scheduler...
archivebox_scheduler-1  | 2024-03-02T14:01:18.279386015Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-02T14:01:18.279438805Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-02T14:01:18.279472504Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-02T14:01:18.279496828Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-02T14:01:18.279521759Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-02T14:01:18.279547996Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-03T00:00:36.663964243Z 
archivebox_scheduler-1  | 2024-03-03T00:00:44.253870007Z 
archivebox_scheduler-1  | 2024-03-03T00:00:51.919116065Z 
archivebox_scheduler-1  | 2024-03-03T00:01:00.930274659Z 
archivebox_scheduler-1  | 2024-03-03T00:01:12.272968052Z 
archivebox_scheduler-1  | 2024-03-03T00:01:21.276574853Z 
archivebox_scheduler-1  | 2024-03-04T00:00:43.127722777Z 
archivebox_scheduler-1  | 2024-03-04T00:00:50.425004264Z 
archivebox_scheduler-1  | 2024-03-04T00:00:57.034483544Z 
archivebox_scheduler-1  | 2024-03-04T00:01:07.993805483Z 
archivebox_scheduler-1  | 2024-03-04T00:01:16.436795384Z 
archivebox_scheduler-1  | 2024-03-04T00:01:22.830716299Z 
archivebox_scheduler-1  | 2024-03-05T00:00:36.826631034Z 
archivebox_scheduler-1  | 2024-03-05T00:00:43.186932558Z 
archivebox_scheduler-1  | 2024-03-05T00:00:50.565603852Z 
archivebox_scheduler-1  | 2024-03-05T00:00:57.326118495Z 
archivebox_scheduler-1  | 2024-03-05T00:01:03.606400772Z 
archivebox_scheduler-1  | 2024-03-05T00:01:10.117535386Z 
archivebox_scheduler-1  | 2024-03-06T00:00:24.470591063Z 
archivebox_scheduler-1  | 2024-03-06T00:00:31.158107143Z 
archivebox_scheduler-1  | 2024-03-06T00:00:37.761570313Z 
archivebox_scheduler-1  | 2024-03-06T00:00:44.836052781Z 
archivebox_scheduler-1  | 2024-03-06T00:00:52.447926243Z 
archivebox_scheduler-1  | 2024-03-06T00:00:59.049561115Z 
archivebox_scheduler-1  | 2024-03-07T00:00:15.856306683Z 
archivebox_scheduler-1  | 2024-03-07T00:00:22.683261531Z 
archivebox_scheduler-1  | 2024-03-07T00:00:29.335330808Z 
archivebox_scheduler-1  | 2024-03-07T00:00:35.974363368Z 
archivebox_scheduler-1  | 2024-03-07T00:00:42.076889848Z 
archivebox_scheduler-1  | 2024-03-07T00:00:48.407490285Z 
archivebox_scheduler-1  | 2024-03-08T00:01:09.995902136Z 
archivebox_scheduler-1  | 2024-03-08T00:01:16.400064838Z 
archivebox_scheduler-1  | 2024-03-08T00:01:22.628996912Z 
archivebox_scheduler-1  | 2024-03-08T00:01:29.169094267Z 
archivebox_scheduler-1  | 2024-03-08T00:01:35.139379491Z 
archivebox_scheduler-1  | 2024-03-08T00:01:41.066133645Z 
archivebox_scheduler-1  | 2024-03-08T20:06:11.702717689Z [i] [2024-03-08 20:06:11] ArchiveBox v0.7.3: archivebox schedule --foreground
archivebox_scheduler-1  | 2024-03-08T20:06:11.702961193Z     > /data
archivebox_scheduler-1  | 2024-03-08T20:06:11.703020091Z 
archivebox_scheduler-1  | 2024-03-08T20:06:14.531508828Z [*] Running 6 ArchiveBox jobs in foreground task scheduler...
archivebox_scheduler-1  | 2024-03-08T20:06:14.531634079Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-08T20:06:14.531665801Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-08T20:06:14.531685314Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-08T20:06:14.531705637Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-08T20:06:14.531721807Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-08T20:06:14.531749276Z   > add --depth=1 "https://****"
archivebox_scheduler-1  | 2024-03-09T00:00:33.473977468Z 
archivebox_scheduler-1  | 2024-03-09T00:00:39.838956997Z 
archivebox_scheduler-1  | 2024-03-09T00:00:46.287759421Z 
archivebox_scheduler-1  | 2024-03-09T00:00:52.161391360Z 
archivebox_scheduler-1  | 2024-03-09T00:00:58.543398437Z 
archivebox_scheduler-1  | 2024-03-09T00:01:05.894195210Z 
archivebox_scheduler-1  | 2024-03-10T00:00:34.661815713Z 
archivebox_scheduler-1  | 2024-03-10T00:00:41.886212927Z 
archivebox_scheduler-1  | 2024-03-10T00:00:48.964084078Z 
archivebox_scheduler-1  | 2024-03-10T00:00:55.804284808Z 
archivebox_scheduler-1  | 2024-03-10T00:01:02.995694282Z 
archivebox_scheduler-1  | 2024-03-10T00:01:10.733616512Z 
archivebox_scheduler-1  | 2024-03-11T00:00:36.632624323Z 
archivebox_scheduler-1  | 2024-03-11T00:00:43.054382100Z 
archivebox_scheduler-1  | 2024-03-11T00:00:50.862239188Z 
archivebox_scheduler-1  | 2024-03-11T00:00:56.759637872Z 
archivebox_scheduler-1  | 2024-03-11T00:01:03.577076534Z 
archivebox_scheduler-1  | 2024-03-11T00:01:10.993614449Z
```

The anonymized URLs are the same in every output. The last log message in django admin is from the day I set everything up and added the URLs: 
![Screenshot 2024-03-11 at 12 34 18](https://github.com/ArchiveBox/ArchiveBox/assets/699106/ccf5855b-849a-480e-832a-5321420002fc)
