### DISCUSSION TITLE
After docker compose `init --setup`, basically all commands result in error: "No archivebox index found in the current directory"

### DISCUSSION THREAD

**Discussion by komali2** [ArchiveBox/ArchiveBox#1666] [Q&A]
I tried installing and initializing per instructions. Here's my docker compose: 

```
version: '2.4'

services:
    archivebox:
        # build: .                              # for developers working on archivebox
        image: ${DOCKER_IMAGE:-archivebox/archivebox:master}
        command: server --quick-init 0.0.0.0:8000
        ports:
            - 8000:8000
        environment:
            - ALLOWED_HOSTS=*                   # add any config options you want as env vars
            - MEDIA_MAX_SIZE=750m
            # - SEARCH_BACKEND_ENGINE=sonic     # uncomment these if you enable sonic below
            # - SEARCH_BACKEND_HOST_NAME=sonic
            # - SEARCH_BACKEND_PASSWORD=SecretPassword
        volumes:
            - ./data:/mnt/media/archivebox/archive
            # - ./archivebox:/app/archivebox    # for developers working on archivebox
   ```

I then do  `docker compose run archivebox init --setup`, fill out the login information and etc. Then i try `docker compose up -d`, followed with e.g. `docker compose run archivebox add 'https://example.com'` or `docker compose run archivebox manage changepassword user` or `docker compose run archivebox manage createsuperuser`, all of which result in error: 

```
[X] No archivebox index found in the current directory.
    /data

    Hint: Are you running archivebox in the right folder?
        cd path/to/your/archive/folder
        archivebox [command]

    Hint: To create a new archive collection or import existing data in this folder, run:
        archivebox init
```

I've tried running these commands in the `/data` directory next to the docker compose file, as well as the directory indicated by my custom volume location (RAID setup).
