### DISCUSSION TITLE
docker-compose start at boot

### DISCUSSION THREAD

**Discussion by ETechTechnologies** [ArchiveBox/ArchiveBox#737] [Q&A] [answered]
How do I have the docker-compose option start at system boot?

**Comment by pirate** [comment, marked as answer]
Just add `restart: always`:
```yaml
services:
    archivebox:
        ...
        restart: always
```
