### DISCUSSION TITLE
Archivebox dont work with Traefik

### DISCUSSION THREAD

**Discussion by phillipunzen** [ArchiveBox/ArchiveBox#959] [Q&A]
Hello everybody!

i try to install archivebox with traefik v2.
And i dont know why i cant reach the website from archivebox.

Can anybody help me?

Thank you!

Here is the `docker.compose.yml`
```yaml
version: '2.4'

services:
  archivebox:
    image: archivebox/archivebox:latest
    command: archivebox server 0.0.0.0:80
    container_name: manuals
    stdin_open: true
    tty: true
    environment:
      - ALLOWED_HOSTS=*
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - USE_COLOR=True
      - SHOW_PROGRESS=False
      - MEDIA_MAX_SIZE=750m
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.manuals.entrypoints=http"
      - "traefik.http.routers.manuals.rule=Host(`manuals.domain.de`)"
      - "traefik.http.middlewares.manuals-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.manuals.middlewares=manuals-https-redirect"
      - "traefik.http.routers.manuals-secure.entrypoints=https"
      - "traefik.http.routers.manuals-secure.rule=Host(`manuals.domain.de`)"
      - "traefik.http.routers.manuals-secure.tls=true"
      - "traefik.http.routers.manuals-secure.tls.certresolver=http"
      - "traefik.http.routers.manuals-secure.service=manuals"
      - "traefik.http.services.manuals.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.manuals-secure.middlewares=secHeaders@file"
      - "com.centurylinklabs.watchtower.enable=true"
```

**Comment by mAAdhaTTah** [comment]
I'm running Archivebox with Traefik without issues. Here's my docker-compose, if that helps:

```yaml
version: "3"

services:
  archivebox:
    image: archivebox/archivebox:{{ service.version }}
    command: server 0.0.0.0:8000
    stdin_open: true
    tty: true
    environment:
      - PUID={{ service_uid }}
      - PGID={{ service_gid }}
      - TZ={{ server_timezone }}
      - USE_COLOR=True
      - SHOW_PROGRESS=False
    volumes:
      - {{ service_data_path }}:/data
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.archivebox.rule=Host(`{{ service.server_name }}`)"
        - "traefik.http.services.archivebox.loadbalancer.server.port=8000"
        - "traefik.http.routers.archivebox.service=archivebox"

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: {{ service.subnet }}
```

This is deployed with Ansible, hence the jinja variables, but maybe this will help?
