### ISSUE TITLE
Question: "GET /admin/login/ HTTP/1.1" 200 11144 spamming logs

### ISSUE THREAD

**Issue by eytschjey** [ArchiveBox/ArchiveBox#1007]
Please excuse me if this has already been discussed or is a total noob question.

I've set up archivebox as a docker container in an effort to have a simple daily backup of a static website. 
I can reach the web GUI and managed to create an account and back up the page. But when looking in the logs, it keeps saying "GET /admin/login/ HTTP/1.1" 200 11144 every few minutes. 

Here's my docker-compose:

```
version: '2.4'

services:
    archivebox:
        # build: .                              
        image: ${DOCKER_IMAGE:-archivebox/archivebox:master}
        command: server --quick-init 0.0.0.0:8000
        ports:
            - 6969:8000
        environment:
            - ALLOWED_HOSTS=*                  
            - MEDIA_MAX_SIZE=750m
            - PUID=1000
            - PGID=1000

        volumes:
            - /home/{myuseraccount}/docker/archivebox:/data

```

Am i doing something wrong?
