### ISSUE TITLE
How do I configure ArchiveBox to persist data on a NAS?

### ISSUE THREAD

**Issue by omniowl** [ArchiveBox/ArchiveBox#1150]
I can see in the documentation it says:

> Try to keep the index.sqlite3 file on local drive (not a network mount), and ideally on an SSD for maximum performance, however the archive/ folder can be on a network mount or spinning HDD.

That sounds great, but when I looked further I didn't seem to find anything suggesting how to achieve this? I'd love to have the sqlite database in my container to save on space and move everything that's archived to my NAS. How would I do that? Did I just miss that in the documentation?

**Comment by pirate** [comment]
It's just a matter of mounting your NAS folder to the `archive/` path, there's not really any setup beyond that required on the ArchiveBox side.

`docker-compose.yml`:
```yaml

services:

  archivebox:
    ...
    volumes:
      - /path/to/your/SSD/archivebox:/data
      - /path/to/your/NAS/archivebox/archive:/data/archive
```
