### ISSUE TITLE
Scheduled jobs added in Docker with `archivebox schedule ...` don't persist when container restarts

### ISSUE THREAD

**Issue by melyux** [ArchiveBox/ArchiveBox#1155]
#### Describe the bug

Adding a new schedule on a feed using `sudo docker compose run archivebox schedule --every=day --depth=1 https://domain.of/feed` says:

`[√] Scheduled new ArchiveBox cron job for user: archivebox (1 jobs are active).`

but subsequently running `sudo docker compose run archivebox schedule --show` says:

`[X] There are no ArchiveBox cron jobs scheduled for your user (archivebox).`

#### Steps to reproduce

docker compose yaml:
```yaml
  archivebox:
    container_name: archivebox
    image: archivebox/archivebox:latest
    command: server --quick-init 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS=*                   # add any config options you want as env vars
      - MEDIA_MAX_SIZE=5000m
      - PUBLIC_INDEX=False
      - PUBLIC_SNAPSHOTS=False
    volumes:
      - ./data:/data
```

Schedule something. Then do `schedule --show`.

#### ArchiveBox version

```logs
0.6.3
ArchiveBox v0.6.3 Cpython Linux Linux-5.10.0-20-amd64-x86_64-with-glibc2.31 x86_64
DEBUG=False IN_DOCKER=True IS_TTY=True TZ=UTC FS_ATOMIC=True FS_REMOTE=True FS_PERMS=644 999:999 SEARCH_BACKEND=ripgrep

[i] Dependency versions:
 √  PYTHON_BINARY         v3.11.3         valid     /usr/local/bin/python3.11                                                   
 √  SQLITE_BINARY         v2.6.0          valid     /usr/local/lib/python3.11/sqlite3/dbapi2.py                                 
 √  DJANGO_BINARY         v3.1.14         valid     /usr/local/lib/python3.11/site-packages/django/__init__.py                  
 √  ARCHIVEBOX_BINARY     v0.6.3          valid     /usr/local/bin/archivebox                                                   

 √  CURL_BINARY           v7.74.0         valid     /usr/bin/curl                                                               
 √  WGET_BINARY           v1.21           valid     /usr/bin/wget                                                               
 √  NODE_BINARY           v18.16.0        valid     /usr/bin/node                                                               
 √  SINGLEFILE_BINARY     v0.3.16         valid     /node/node_modules/single-file/cli/single-file                              
 √  READABILITY_BINARY    v0.0.2          valid     /node/node_modules/readability-extractor/readability-extractor              
 √  MERCURY_BINARY        v1.0.0          valid     /node/node_modules/@postlight/mercury-parser/cli.js                         
 √  GIT_BINARY            v2.30.2         valid     /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY      v2023.03.04     valid     /usr/local/bin/yt-dlp                                                       
 √  CHROME_BINARY         v112.0.5615.138  valid     /usr/bin/chromium                                                           
 √  RIPGREP_BINARY        v12.1.1         valid     /usr/bin/rg                                                                 

[i] Source-code locations:
 √  PACKAGE_DIR           22 files        valid     /app/archivebox                                                             
 √  TEMPLATES_DIR         3 files         valid     /app/archivebox/templates                                                   
 -  CUSTOM_TEMPLATES_DIR  -               disabled                                                                              

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled                                                                              
 -  COOKIES_FILE          -               disabled                                                                              

[i] Data locations:
 √  OUTPUT_DIR            5 files @       valid     /data                                                                       
 √  SOURCES_DIR           0 files         valid     ./sources                                                                   
 √  LOGS_DIR              1 files         valid     ./logs                                                                      
 √  ARCHIVE_DIR           0 files         valid     ./archive                                                                   
 √  CONFIG_FILE           81.0 Bytes      valid     ./ArchiveBox.conf                                                           
 √  SQL_INDEX             204.0 KB        valid     ./index.sqlite3  
```

**Comment by pirate** [comment]
The schedule commands write to your local crontab file, can you check your user's crontab to see if they're in there?

**Comment by pirate** [comment]
Wait nvm I saw you're in docker, I'll check it out.

**Comment by melyux** [comment]
The contents of /etc/cron.d inside the container (after running the schedule command) are these:

placeholder
e2scrub_all

**Comment by pirate** [comment]
I think it may be more trouble than it's worth trying to use cron within the Docker container, as the container is not designed to persist any state other than the archivebox data folder (which is why your crontab gets wiped out every time the container is re-created).

The recommended approach is the one we have as a commented-out example in the provided [`docker-compose.yml`](https://github.com/ArchiveBox/ArchiveBox/blob/dev/docker-compose.yml#L64):

```yaml
  archivebox_scheduler:
    image: archivebox/archivebox:dev
    command: schedule --foreground --every=day --depth=1 'https://getpocket.com/users/USERNAME/feed/all'
    volumes:
      - ./data:/data
```

Using this pattern you would add a new yaml service definition block for every scheduled job you need to your `docker-compose.yml`. The example above shows archiving a pocket RSS feed, but you could copy paste this block several times and alter the URL and `--every=N` argument to archive multiple sites on different schedules.

This will be streamlined in the future once we add support for scheduling jobs via the UI: https://github.com/ArchiveBox/ArchiveBox/issues/578 (subscribe here for updates on progress).
