### ISSUE TITLE
Question: Sonic auto index

### ISSUE THREAD

**Issue by g1t-lab** [ArchiveBox/ArchiveBox#1170]
Hello There
I've configured Docker stack
Sonic doesn't index new items.
I can search content in new archived sites only after I start "archivebox update --index-only" in Docker
Could you please help me to know how to invetigate and fix it?
Also I use NginxProxyManager as reverse proxy, so 8000 is not exposed to docker host

My config:

```yaml
version: '2.4'

services:
    archivebox:
        image: ${DOCKER_IMAGE:-archivebox/archivebox:latest}
        restart: unless-stopped
        command: server --quick-init 0.0.0.0:8000
        #ports:
        #    - 8000:8000
        environment:
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}                   # add any config options you want as env vars
            - MEDIA_MAX_SIZE=${MEDIA_MAX_SIZE}
            - SEARCH_BACKEND_ENGINE=${SEARCH_BACKEND_ENGINE}     # uncomment these if you enable sonic below
            - SEARCH_BACKEND_HOST_NAME=${SEARCH_BACKEND_HOST_NAME}
            - SEARCH_BACKEND_PASSWORD=${SEARCH_BACKEND_PASSWORD}
            - TIMEOUT=${TIMEOUT}
            - MEDIA_TIMEOUT=${MEDIA_TIMEOUT}
            - SAVE_FAVICON=${SAVE_FAVICON}
            - SAVE_WGET=${SAVE_WGET}
            - SAVE_WARC=${SAVE_WARC}
            - SAVE_PDF=${SAVE_PDF}
            - SAVE_SCREENSHOT=${SAVE_SCREENSHOT}
            - SAVE_DOM=${SAVE_DOM}
            - SAVE_SINGLEFILE=${SAVE_SINGLEFILE}
            - SAVE_READABILITY=${SAVE_READABILITY}
            - SAVE_MERCURY=${SAVE_MERCURY}
            - SAVE_GIT=${SAVE_GIT}
            - SAVE_MEDIA=${SAVE_MEDIA}
            - SAVE_ARCHIVE_DOT_ORG=${SAVE_ARCHIVE_DOT_ORG}
            - CHECK_SSL_VALIDITY=${CHECK_SSL_VALIDITY}
            - SAVE_WGET_REQUISITES=${SAVE_WGET_REQUISITES}
            - PUBLIC_INDEX=${PUBLIC_INDEX}
            - PUBLIC_SNAPSHOTS=${PUBLIC_SNAPSHOTS}
            - PUBLIC_ADD_VIEW=${PUBLIC_ADD_VIEW} 
        volumes:
            - /srv/archivebox/archivebox_data:/data
            - /srv/archivebox/archivebox_archive:/data/archive
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        networks:
            - npm-external
            - archivebox-internal

    sonic:
        image: valeriansaliou/sonic:v1.3.0
        restart: unless-stopped
        depends_on:
            - archivebox
        expose:
            - 1491
        environment:
            - SEARCH_BACKEND_PASSWORD=${SEARCH_BACKEND_PASSWORD}
        volumes:
            - /srv/archivebox/sonic_cfg/sonic.cfg:/etc/sonic.cfg:ro
            - /srv/archivebox/sonic_data/:/var/lib/sonic/store
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        networks:
            - archivebox-internal

networks:
    npm-external:
      external: true
    archivebox-internal:
      external: true
```

**Comment by IvanVas** [comment]
+1

**Comment by pirate** [comment]
Can you set `log_level = "debug"` in `sonic.cfg`, and `DEBUG=True` on the archivebox environment, then restart everything.

Check the output / post it here from `docker compose logs` when you add a new URL.

Also note there have been some changes in v0.7.2 to the docker-compose.yml file, I recommend upgrading your container version and checking for any differences you might want to copy over.
I would also not sync `/etc/timezone:/etc/timezone:ro` with the archivebox container, as archivebox must always be run in UTC and does not support server side timezone changes (only client-side).

**Comment by pirate** [comment]
Closing as inactive for now, feel free to comment back if you're still having issues on `:dev` and I can reopen it.

**Comment by dehlen** [comment]
Hey, I am currently experiencing the same issue. Happy to provide more logs when I am back at my computer tomorrow. I am only adding new URLs via the scheduler. Could this be related? I just triggered the update --index-only but this is very time consuming as I have quite a large library of snapshots. I just stumbled upon this issue because I was searching for something in my library i was very sure about should be in the index. I found my saved article with a valid readability representation containing my keyword but search did not return this result.

**Comment by pirate** [comment]
Ok, I can investigate but please open a new issue and share logs + `archivebox version` output when you get a chance.

**Comment by dehlen** [comment]
Nevermind I had a look this morning at my config again and I think I found the issue. So here is my assumption:
I use docker compose. In it I use the archive box service with these environment variables:
```
- SEARCH_BACKEND_ENGINE=sonic
- SEARCH_BACKEND_HOST_NAME=sonic
- SEARCH_BACKEND_PASSWORD=MY_PASSWORD
```

I also setup the archive box scheduler by adding this volume to the archive box service:
`- path/to/crontabs:/var/spool/cron/crontabs`

Then I setup the sonic service:
```
sonic:
        image: valeriansaliou/sonic:latest
        container_name: sonic
        expose:
            - 1491
        environment:
            - SEARCH_BACKEND_PASSWORD=MY_PASSWORD
        volumes:
            - path/to/sonic.cfg:/etc/sonic.cfg:ro
            - path/to/sonic:/var/lib/sonic/store
```

And I setup the archive box scheduler service:
```
archivebox_scheduler:
  build: path/to/Dockerfile
  command: schedule --foreground
  environment:
      - MEDIA_MAX_SIZE=750m # increase this number to allow archiving larger audio/video files
      - TIMEOUT=120 # increase if you see timeouts often during archiving / on slow networks
      - ONLY_NEW=True # set to False to retry previously failed URLs when re-adding instead of skipping them
      # - CHECK_SSL_VALIDITY=True         # set to False to allow saving URLs w/ broken SSL certs
      - PUID=1026 # set to your host user's UID & GID if you encounter permissions issues
      - PGID=100
      - SAVE_TITLE=True
      - SAVE_FAVICON=True
      - SAVE_WGET=True
      - SAVE_WARC=True
      - SAVE_PDF=False
      - SAVE_SCREENSHOT=False
      - SAVE_DOM=False
      - SAVE_SINGLEFILE=True
      - SAVE_READABILITY=True
      - SAVE_GIT=False
      - SAVE_MEDIA=False
      - SUBMIT_ARCHIVE_DOT_ORG=False
      - SAVE_ARCHIVE_DOT_ORG=False
  volumes:
      - path/to/data:/data
      - path/to/crontabs:/var/spool/cron/crontabs
```

What was missing was the SEARCH_BACKEND related environment variables for my scheduler service. So whenever my scheduler was running archive box add was executed but the scheduler service adding the URLs did not know about the sonic backend. I added the 3 SEARCH_BACKEND related env variables to my scheduler service as well and now it seems to be working. I checked whether I could find a new link by connecting to the scheduler service container and running archivebox schedule --run-all. This executed all my scheduled scripts and added new links by that which immediately were findable via search. Previously this was not the case for URLs added via the scheduler. When I added URLs from the web UI all worked flawlessly. So I think this probably caused me the above problems.
