### ISSUE TITLE
Bug: docker - error: exec: "bash": executable file not found in $PATH

### ISSUE THREAD

**Issue by eleaner** [ArchiveBox/ArchiveBox#1216]
#### Describe the bug
Docker compose when started reports 
```
docker compose logs -f
archivebox  | error: exec: "bash": executable file not found in $PATH
archivebox  | error: exec: "bash": executable file not found in $PATH
archivebox  | error: exec: "bash": executable file not found in $PATH
archivebox  | error: exec: "bash": executable file not found in $PATH
archivebox  | error: exec: "bash": executable file not found in $PATH
archivebox exited with code 1
```

it seems that bash sits in /bin/bash
but docker_entrypoint.sh expects #!/usr/bin/env bash

#### Steps to reproduce
1. create docker-compose.yml
```
version: '3.7'

services:
    archivebox:
        image: ${DOCKER_IMAGE:-archivebox/archivebox:latest}
        container_name: archivebox
        stdin_open: true
        tty: true
        ports:
            - 8000:8000
        environment:
            - USE_COLOR=True
            - SHOW_PROGRESS=False
        volumes:
            - ./data:/data
```
2. docker compose up -d
3. docker compose logs -f

#### ArchiveBox version
archivebox/archivebox:latest
