### ISSUE TITLE
Question: shell commands passed in to Docker-Compose archivebox are getting executed as root and failing

### ISSUE THREAD

**Issue by Brancliff** [ArchiveBox/ArchiveBox#1258]
I'm sorta new to this sort of thing, but I thought if you wanted to run these containers as root, you'd say something like "privileged: true" in the docker-compose or something. I didn't, but I'm still getting errors trying to spin this up.

Here's my docker-compose:
```
version: '3.3'
services:
  archivebox:
    image: ${DOCKER_IMAGE:-archivebox/archivebox:dev}
    command: server --quick-init 0.0.0.0:8000
    ports:
    - 8000:8000
    volumes:
    - /share/CE_CACHEDEV1_DATA/Library/Containers/ArchiveBox:/data
```

And here's the error I get when trying to make a new user:

```
root@f0fb2b38ca59:/data# archivebox manage createsuperuser
find: ‘/root/.config/chromium/Crash Reports/pending/’: No such file or directory
[i] [2023-10-29 08:29:22] ArchiveBox v0.6.3: archivebox manage createsuperuser
    > /data

[!] ArchiveBox should never be run as root!
    For more information, see the security overview documentation:
        https://github.com/ArchiveBox/ArchiveBox/wiki/Security-Overview#do-not-run-as-root
root@f0fb2b38ca59:/data# 
```

I mean, I can understand that these commands start with root@something, I just don't know what I need to put in my docker-compose to **not** do that
