### ISSUE TITLE
Fix Docker image builds CI messing up `:latest`, `:stable`, and `:dev` tags

### ISSUE THREAD

**Issue by stanthewizzard** [ArchiveBox/ArchiveBox#1414]
Starting log:
```
archivebox  | [i] [2024-04-24 08:20:42] ArchiveBox v0.7.2: archivebox server --quick-init 0.0.0.0:8000
archivebox  |     > /data
archivebox  | 
archivebox  | [+] Initializing a new ArchiveBox v0.7.2 collection...
archivebox  | ----------------------------------------------------------------------
archivebox  | 
archivebox  | [+] Building archive folder structure...
archivebox  |     + ./archive, ./sources, ./logs...
archivebox  |     + ./ArchiveBox.conf...
archivebox  | 
archivebox  | [+] Building main SQL index and running initial migrations...
archivebox  | Traceback (most recent call last):
archivebox  |   File "/usr/local/bin/archivebox", line 8, in <module>
archivebox  |     sys.exit(main())
archivebox  |              ^^^^^^
archivebox  |   File "/app/archivebox/cli/__init__.py", line 140, in main
archivebox  |     run_subcommand(
archivebox  |   File "/app/archivebox/cli/__init__.py", line 80, in run_subcommand
archivebox  |     module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
archivebox  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/app/archivebox/cli/archivebox_server.py", line 64, in main
archivebox  |     server(
archivebox  |   File "/app/archivebox/util.py", line 116, in typechecked_function
archivebox  |     return func(*args, **kwargs)
archivebox  |            ^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/app/archivebox/main.py", line 1308, in server
archivebox  |     run_subcommand('init', subcommand_args=['--quick'], stdin=None, pwd=out_dir)
archivebox  |   File "/app/archivebox/cli/__init__.py", line 80, in run_subcommand
archivebox  |     module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
archivebox  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/app/archivebox/cli/archivebox_init.py", line 43, in main
archivebox  |     init(
archivebox  |   File "/app/archivebox/util.py", line 116, in typechecked_function
archivebox  |     return func(*args, **kwargs)
archivebox  |            ^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/app/archivebox/main.py", line 362, in init
archivebox  |     for migration_line in apply_migrations(out_dir):
archivebox  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/app/archivebox/util.py", line 116, in typechecked_function
archivebox  |     return func(*args, **kwargs)
archivebox  |            ^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/app/archivebox/index/sql.py", line 145, in apply_migrations
archivebox  |     call_command("makemigrations", interactive=False, stdout=null)
archivebox  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 168, in call_command
archivebox  |     return command.execute(*args, **defaults)
archivebox  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 371, in execute
archivebox  |     output = self.handle(*args, **options)
archivebox  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 85, in wrapped
archivebox  |     res = handle_func(*args, **kwargs)
archivebox  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/makemigrations.py", line 87, in handle
archivebox  |     loader = MigrationLoader(None, ignore_no_migrations=True)
archivebox  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 53, in __init__
archivebox  |     self.build_graph()
archivebox  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 210, in build_graph
archivebox  |     self.load_disk()
archivebox  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 112, in load_disk
archivebox  |     migration_module = import_module(migration_path)
archivebox  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
archivebox  |     return _bootstrap._gcd_import(name[level:], package, level)
archivebox  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
archivebox  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
archivebox  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
archivebox  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
archivebox  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
archivebox  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
archivebox  |   File "/app/archivebox/api/migrations/0001_initial.py", line 9, in <module>
archivebox  |     class Migration(migrations.Migration):
archivebox  |   File "/app/archivebox/api/migrations/0001_initial.py", line 22, in Migration
archivebox  |     ('token', models.CharField(default=auth.models.hex_uuid, max_length=32, unique=True)),
archivebox  |                                        ^^^^
archivebox  | NameError: name 'auth' is not defined
archivebox exited with code 1
```

#### Describe the bug
docker not starting

#### Steps to reproduce
docker compose

```
services:
    archivebox:
      image: archivebox/archivebox:latest
      container_name: archivebox
      ports:
        - 8019:8000
      volumes:
        - ./data:/data
      environment:
        - ADMIN_USERNAME=admin            # create an admin user on first run with the given user/pass combo
        - ADMIN_PASSWORD=Cgy6J5Aiw0gHsobyrrHUU (it"s a dumy pass)
        - ALLOWED_HOSTS=*                   # restrict this to only accept incoming traffic via specific domain name
        - PUBLIC_INDEX=True                 # set to False to prevent anonymous users from viewing snapshot list
        - PUBLIC_SNAPSHOTS=True             # set to False to prevent anonymous users from viewing snapshot content

```

#### ArchiveBox version

docker latest image (24/04/2024)

Thanks for help
