### ISSUE TITLE
Can't start a container using a named volume

### ISSUE THREAD

**Issue by zblesk** [ArchiveBox/ArchiveBox#471]
#### Describe the bug

Can't get ArchiveBox to run with data in a named volume. If I just map a standard folder, it works though.

#### Steps to reproduce

I'm trying to use docker-compose. My file:

```
version: "3"

services:
  archivebox:
    image: nikisweeting/archivebox
    volumes:
      - archivebox_files:/data
    ports:
      - 8000:8000 

volumes:
  archivebox_files:
```

First I run `docker-compose up --no-start` to create the container and volume without starting anything. 

Then, running `docker-compose run archivebox init` keeps failing on permission errors. I tried creating the folders manually within the volume, and setting everything in the volume to mode 777, but nothing helped.

#### Screenshots or log output

![image](https://user-images.githubusercontent.com/4245227/92655341-86c02180-f2f1-11ea-8ebb-2a66a0d4276f.png)

```


#### Software versions

 - OS: Ubuntu Server 18 LTS
 - ArchiveBox version:        latest docker image
