### ISSUE TITLE
Question: scheduler, docker-compose. How to add multiple ulrs?

### ISSUE THREAD

**Issue by akhilleusuggo** [ArchiveBox/ArchiveBox#921]
I've tried multiples ways, no errors. But only it picks the first url.

```
........................
scheduler:
        image: archivebox/archivebox:latest
        command: >
           schedule "--foreground --every=hour --depth=1 https://example/rss.xml &&
                    --foreground --every=hour --depth=1 https://example2/rss.xml"
        environment:
..........................
```

Tried as suggested in forums and around the internet using `bash -c` and `sh -cx`, but only errors since doesn't recognize them.

How can it be achieved? Create a new scheduler compose block?

**Comment by pirate** [comment]
I recommend making separate containers for each, or have one container just run `--foreground` without a URL (which will run all the scheduled tasks added via CLI in one container).

**Comment by melyux** [comment]
I tried making the scheduler container, but it just gives this error and exits:

`[X] You must schedule some jobs first before running in foreground mode.`

I tried adding a scheduled job using:

`sudo docker compose run archivebox-scheduler schedule --every=day --depth=1 https://blahblahblah.com/feed`

and it says:

`[√] Scheduled new ArchiveBox cron job for user: archivebox (1 jobs are active).`

but the scheduler job still gives the same error as above.

My docker compose for the scheduler is this:

```
  archivebox-scheduler:
    container_name: archivebox-scheduler
    image: archivebox/archivebox:latest
    command: schedule --foreground
    environment:
      - USE_COLOR=True
      - SHOW_PROGRESS=False
    volumes:
      - ./data:/data
```

This is all very confusing. How can I add scheduled jobs so that the scheduler task picks them up?
