### ISSUE TITLE
Question: Mounting symlink'd index.sqlite3 on SSD when using docker-compose

### ISSUE THREAD

**Issue by akhilleusuggo** [ArchiveBox/ArchiveBox#945]
Hello,

I've tried many ways to make it work, but I can't achieve to have the database hosted outside of the /data directory.
I'm running the project on ZFS (hard drives), the performance is O.K, but it start to get slow on the DB side, and when trying to add multiple links error 500 starts occurring.
You suggest running the database at the least on SSD https://github.com/ArchiveBox/ArchiveBox#storage-requirements , but doesn't seem to work with docker-compose, or I'm unable to mount it properly.

```
version: '2.4'   # '3.9' or greater also works

services:
    archivebox:
        # build: .                              # for developers working on archivebox
        image: ${DOCKER_IMAGE:-archivebox/archivebox:master}
        command: server --quick-init 0.0.0.0:8000
        ports:
            - 8000:8000
        environment:
            - ALLOWED_HOSTS=*                   # add any config options you want as env vars
            - SAVE_MEDIA=False
            #- MEDIA_MAX_SIZE=750m
            # - SEARCH_BACKEND_ENGINE=sonic     # uncomment these if you enable sonic below
            # - SEARCH_BACKEND_HOST_NAME=sonic
            # - SEARCH_BACKEND_PASSWORD=SecretPassword
        volumes:
            - /docker/archivebox/data:/data
```

My home directory is an NVMe SSD, I would like to have the `index.sqlite3` on `/home/user/data/index.sqlite3`

Tried symbolic link, but does fail. Compose doesn't start, looping errors.
Tried to add a volume like this, but keeps recreating the database from scratch. 

```
 volumes:
            - /docker/archivebox/data:/data
            - /home/user/data/index.sqlite3:/data/index.sqlite3
```

Any proper way of mounting it?

**Comment by akhilleusuggo** [comment]
I've managed to fix my issue. Seems like docker is not very friendly with symbolic links.

The mount folder/files must be identical of the docker.

In this example, I had to create a `/data` folder on the host machine. Copy to it the index.sqlite3
Expose the index.sqlite3 in the docker container volumes.

`/data/index.sqlite3:/data/index.sqlite3`

Not sure way, but the script keeps creating a dummy file `index.sqlite3 `

**Comment by pirate** [comment]
Correct, docker doesn't work to mount symbolic links as volumes.
If the mounted file is not valid inside docker it will try to overwrite it an create that empty index.sqlite3 you're seeing.

Hard links should work however, or you can mount the symlink destination as a volume as well (at the same path inside and outside of docker) and then it should work.

**Comment by akhilleusuggo** [comment]
Could you explain what do you mean by 

> you can mount the symlink destination as a volume as well (at the same path inside and outside of docker)

If you could provide an example I'd appreciate it.

**Comment by pirate** [comment]
For example if you have this folder layout on the host:

```
~/archivebox
    data/
        index.sqlite3 -> /media/someSSD/archivebox/index.sqlite (symlink)
        archive/
            1234566778/
            ...
        ...
```

Then you would need to mount it like so in `docker-compose.yml`:
```yaml
services:
    archivebox:
        ...
        volumes:
            - ./data:/data
            - /media/someSSD/archivebox/index.sqlite:/media/someSSD/archivebox/index.sqlite
```
(note the symlink path must be mounted to the same path as it is on the host inside docker)
